# Generated by Django 5.2.7 on 2025-10-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_type_campaign_name_campaign_average_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='average_income',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='campaignuser',
            unique_together={('user', 'campaign')},
        ),
    ]
