# Generated by Django 5.2.7 on 2025-10-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_campaign_average_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='average_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
